name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    name: Lint, Unit Test, E2E Test, Build
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run Unit Tests with Coverage
        run: npm run test:coverage

      - name: Upload Coverage Report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/lcov-report

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright E2E Tests
        run: npx playwright test

      - name: Upload Playwright Report
        if: success() && always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
